# Generated by Django 4.0.1 on 2022-02-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar/default.bmp', upload_to='images/avatar/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
