# Generated by Django 4.0.1 on 2022-02-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_text',
            field=models.TextField(max_length=500, verbose_name='Превью'),
        ),
    ]
