# Generated by Django 4.0.1 on 2022-02-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(blank=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
